import { defineConfig } from '@umijs/max';

export default defineConfig({
  title: 'SSS Admin',
  hash: true,
  access: {},
  model: {},
  initialState: {},
  request: {},
  layout: false,
  routes: [
    { path: '/login', component: '@/pages/login', layout: false },
    { path: '/403', component: '@/pages/403', layout: false },
    { path: '/404', component: '@/pages/404', layout: false },
    { path: '/redirect/:path(.*)', component: '@/pages/redirect', layout: false },
    { path: '/user/profile', component: '@/pages/user/profile', layout: false },
    { path: '/user/message', component: '@/pages/user/message', layout: false },
    { path: '/user/notice', component: '@/pages/user/notice', layout: false },
    {
      path: '/',
      component: '@/layouts',
      routes: [
        { path: '/dashboard/workplace', component: '@/pages/dashboard/workplace' },
        { path: '/dashboard/analysis', component: '@/pages/dashboard/analysis' },
        { path: '/dashboard/cockpit', component: '@/pages/dashboard/cockpit' },
        { path: '/dashboard/task', component: '@/pages/dashboard/task' },
        { path: '/dashboard/category', component: '@/pages/dashboard/category' },
        { path: '/dashboard/project-schedule', component: '@/pages/dashboard/project-schedule' },
        { path: '/dashboard/resource-board', component: '@/pages/dashboard/resource-board' },
        { path: '/system/user', component: '@/pages/system/user' },
        { path: '/system/role', component: '@/pages/system/role' },
        { path: '/system/menu', component: '@/pages/system/menu' },
        { path: '/system/dept', component: '@/pages/system/dept' },
        { path: '/system/dict', component: '@/pages/system/dict' },
        { path: '/system/notice', component: '@/pages/system/notice' },
        { path: '/system/file', component: '@/pages/system/file' },
        { path: '/system/config/site', component: '@/pages/system/config/site' },
        { path: '/system/config/login', component: '@/pages/system/config/login' },
        { path: '/system/config/security', component: '@/pages/system/config/security' },
        { path: '/system/config/mail', component: '@/pages/system/config/mail' },
        { path: '/system/config/storage', component: '@/pages/system/config/storage' },
        { path: '/system/config/sms', component: '@/pages/system/config/sms' },
        { path: '/system/config/client', component: '@/pages/system/config/client' },
        { path: '/monitor/log/login', component: '@/pages/monitor/log/login' },
        { path: '/monitor/log/operation', component: '@/pages/monitor/log/operation' },
        { path: '/monitor/online', component: '@/pages/monitor/online' },
        { path: '/monitor/sms/log', component: '@/pages/monitor/sms/log' },
        { path: '/schedule/job', component: '@/pages/schedule/job' },
        { path: '/schedule/log', component: '@/pages/schedule/log' },
        { path: '/open/app', component: '@/pages/open/app' },
        { path: '/tenant/management', component: '@/pages/tenant/management' },
        { path: '/tenant/package', component: '@/pages/tenant/package' },
        { path: '/code/generator', component: '@/pages/code/generator' },
      ],
    },
    { path: '/*', redirect: '/404' },
  ],
  proxy: {
    '/sss-task': {
      target: 'https://booking-dev.3s-guojian.com',
      changeOrigin: true,
    },
  },
  plugins: [],
  tailwindcss: {},
  antd: {
    dark: false,
    configProvider: {},
  },
  theme: {
    'primary-color': '#165DFF',
  },
});
